<?php /** @var Core_Block_Abstract $this */ ?>
<head>
    <?php $this->getChunk('admin/chunks/_head.phtml', 'Core_Block_Page_Head') ?>
</head>
<body>
<?php $this->getChunk('admin/chunks/_menu.phtml', '\Admin\Block\Page\Menu') ?>
<div class="container">
    <div class="row">
        <div class="col-sm-5">
            <?php echo $this->getData('contentleft') ?>
        </div>
        <div class="col-sm-5">
            <?php echo $this->getData('contentright') ?>
        </div>
    </div>
</div>
</body>
<?php $this->getChunk('admin/chunks/_footer.phtml') ?>
