<?php
/** @var \Customer\Block\Photo\Index $this */
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <?php echo $this->getCustomerInfo()->getName() ?>
    </div>
    <div class="panel-body">
        <?php
          if(count($this->getAllFile()) == 0) {
              echo \Core\Helper::__('Directory is empty');
          }
        ?>
        <?php foreach ($this->getAllFile() as $_file): ?>
            <div class="row">
                <div class="col-lg-1">
                    <?php if ($_file['type'] == 'directory'): ?>
                        <span class="glyphicon glyphicon-folder-open"></span>
                    <?php else: ?>
                        <img src="<?php echo $this->getUrlToPicture() ?><?php echo $_file['name']?>" width="70" height="70" class="img-rounded">
                    <?php endif; ?>
                </div>
                <div class="col-lg-8">
                    <?php if ($_file['type'] == 'directory'): ?>
                    <a href='<?php echo $_SERVER['REQUEST_URI'] ?>path/<?php echo $_file['name'] ?>'><?php echo $_file['name'] ?></a>
                    <?php else: ?>
                    <a href="<?php echo $this->getUrlToPicture() ?><?php echo $_file['name']?>"><?php echo $_file['name'] ?></a>
                    <?php endif;?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<?php if($_SESSION['customer_id'] == \Core\App::getParams()['id']): ?>
<form action="<?php echo \Core\Helper::getUrl('customer/photo/upload') ?>" method="post" enctype="multipart/form-data">
    <input type="file" class="file_upload" name="file">
    <input type="hidden" name="url" value="<?php echo $_SERVER['REQUEST_URI'] ?>">
    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-upload"></span> </button>
</form>
<?php endif; ?>
