<form data-toggle="validator" action="<?php echo \Core\App::getBaseUrl() ?>contact/index/saveAttrib/" method="post" role="form" class="form-horizontal">
    <input type="hidden" name="url" value="<?php \Core\App::getBaseUrl() ?>contact/create/addAttribute/">
    <div class="form-group">
        <label class="col-sm-2 control-label" for="name">Name attribute:</label>
        <div class="col-sm-10">
            <input class="form-control" id="name" type="text" placeholder="name" name="name" required>
            <div class="help-block with-errors"></div>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="place">Placeholder:</label>
        <div class="col-sm-10">
            <input class="form-control" type="text" placeholder="placeholder" name="placeholder">
            <div class="help-block with-errors"></div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <label>
                <select id="type_input" name="type_input" class="form-control">
                    <option value="text">text</option>
                    <option value="email">Email validation as mail</option>
                    <option value="url">Site url vildation as url</option>
                    <option value="textarea">textarea</option>
                </select> Chose input type
            </label>
            <div class="help-block with-errors"></div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label>
                    <input id="requir" type="checkbox" name="required" value="required"> Required
                    <div class="help-block with-errors"></div>
                </label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label>
                    <input id="sing" class="checkbox" type="checkbox" name="show_in_greed" value="1">
                    Show in greed
                </label>
                <div class="help-block with-errors"></div>
            </div>
        </div>
    </div>
    <input class="btn btn-success col-sm-offset-10" type="submit" value="Save">
</form>