<div class="page-header">
    <h1>Create new menu item</h1>
</div>

<form role="form" action="<?php echo Core_Helper::getUrl('pages/index/saveMenu') ?>" method="post">
    <div class="row">
        <div class="col-sm-3">
            <div class="well">
                <ul class="nav nav-list">
                    <?php foreach ($this->getMenu() as $key => $menu): ?>
                        <li><label><?php echo $menu->title ?></label>
                            <?php if (isset($menu->child)): ?>
                                <ul class="nav nav-list tree">
                                    <?php foreach ($menu->child as $_child): ?>
                                        <li><a href=""><?php echo $_child->title ?></a> </li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="form-group">
                <label for="parent">Parent menu:</label>
                <select class="form-control" name="parent" id="parent">
                    <option value="main">Main menu</option>
                    <?php foreach ($this->getMenu() as $menu): ?>
                        <option value="<?php echo $menu->key ?>"><?php echo $menu->title ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="key">Url key:</label>
                <input id="key" name="key" class="form-control" type="text" required placeholder="Menu key">
            </div>
            <input type="hidden" name="back_url" value="<?php echo Core_Helper::getUrl('pages/index/addMenu') ?>">
            <div class="form-group">
                <label for="title">Title menu:</label>
                <input id="title" name="title" class="form-control" type="text" required placeholder="Menu name">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Save menu</button>
            </div>
        </div>
    </div>
</form>