<div class="page-header">
    <h1><?php echo \Core\Helper::__('Create new page') ?></h1>
</div>
<?php
$page = $this->getPage();
$page = reset($page);
?>
<form role="form" action="<?php echo \Core\Helper::getUrl('pages/index/savePage') ?>" method="post">
    <div class="row">
        <div class="col-sm-3">
            <div class="well">
                <ul class="nav nav-list">
                    <?php foreach ($this->getMenu() as $key => $menu): ?>
                        <li><label><?php echo $menu->title ?></label>
                            <?php if (isset($menu->child)): ?>
                                <ul class="nav nav-list tree">
                                    <?php foreach ($menu->child as $_child): ?>
                                        <li><a href=""><?php echo $_child->title ?></a></li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="form-group">
                <label for="parent"><?php echo \Core\Helper::__('Menu') ?>:</label>
                <select multiple="multiple" class="form-control" name="menu_key[]" id="parent">
                    <option value="main"><?php echo \Core\Helper::__('Main menu') ?></option>
                    <?php //print_r(($page));die;?>
                    <?php foreach ($this->getMenu() as $menu): ?>
                        <option value="<?php echo $menu->key ?>"<?php
                        if (isset($page->menu_key)) {
                            if (!is_array($page->menu_key)) {
                                $page->menu_key = array($page->menu_key);
                            }
                            if (array_search($menu->key, $page->menu_key) !== false) echo 'selected';
                        }
                        ?>><?php echo $menu->title ?></option>
                        <?php if (isset($menu->child)): ?>
                            <?php foreach ($menu->child as $_child): ?>
                                <option value="<?php echo $_child->key ?>" <?php
                                if (isset($page->menu_key)) {
                                    if (array_search($_child->key, $page->menu_key) !== false) echo 'selected';
                                }
                                ?>><?php echo $_child->title ?></option>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="key"><?php echo \Core\Helper::__('Url key') ?>:</label>
                <input id="key" name="key" class="form-control" type="text"
                       value="<?php if (isset($page->key)) echo $page->key ?>" required
                       placeholder="<?php echo \Core\Helper::__('Url key') ?>">
            </div>
            <input type="hidden" name="back_url"
                   value="<?php echo \Core\Helper::getUrl('pages/index/addPage') ?><?php if (isset(\Core\App::getParams()['id'])) echo '/id/' . \Core\App::getParams()['id'] ?>">
            <div class="form-group">
                <label for="title"><?php echo \Core\Helper::__('Title') ?>:</label>
                <input id="title" name="title[en]" class="form-control" type="text"
                          value="<?php if (isset($page->title->en)) echo $page->title->en ?>" required
                          placeholder="<?php echo \Core\Helper::__('Title') ?>">
            </div>
            <div class="form-group">
                <label for="short-content"><?php echo \Core\Helper::__('Short content') ?>:</label>
                <textarea class="form-control" name="short_content[en]"
                          id="short-content"><?php if (isset($page->short_content->en)) echo $page->short_content->en ?></textarea>
            </div>
            <div class="form-group">
                <label for="content"><?php echo \Core\Helper::__('Content') ?>:</label>
                <textarea class="form-control" id="tiny_edit" name="content[en]"
                          id="content"><?php if (isset($page->content->en)) echo $page->content->en ?></textarea>
            </div>
            <div class="form-group">
                <?php if (isset(\Core\App::getParams()['id'])): ?>
                    <input type="hidden" name="id" value="<?php echo \Core\App::getParams()['id'] ?>">
                <?php endif; ?>
                <button type="submit" class="btn btn-success"><?php echo \Core\Helper::__('Save') ?></button>
            </div>
        </div>
    </div>
</form>
<script>
    window.onload = function(){
        tinymce.init({ selector:'#tiny_edit' });
    }
</script>