<div class="page-header">
    <h1>Pages modules</h1>
    <p>
        <a class="btn-success btn "
           href="<?php echo Core_Helper::getUrl('pages/index/addPage')?>">create page</a>
        <a class="btn-success btn "
           href="<?php echo Core_Helper::getUrl('pages/index/addMenu')?>">create menu</a>
    </p>
</div>
<div class="table-responsive">
    <table class="table table-striped">
        <thead class="table-success">
        <tr>
            <td>Title</td>
            <td>Url</td>
            <td>Action</td>
        </tr>
        </thead>
        <tbody>
            <?php foreach($this->getPages() as $key => $_page): ?>
                <tr>
                    <td><?php echo $_page->title?></td>
                    <td><?php echo $_page->key?></td>
                    <td>
                        <a href="<?php echo Core_Helper::getUrl('pages/index/addPage/').'/id/'.$_page->_id ?>" >Edit</a>
                        <a href="<?php echo Core_Helper::getUrl('pages/index/deletePage/').'/id/'.$_page->_id ?>" >Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>