<?php /** @var \Index\Block\Index $this */ ?>
<center><h1>Простой название сайта</h1></center>
<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Чем мы отличаемся от других?
            </div>
            <div class="panel-body">
                А ни чем
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Чем мы отличаемся от других?
            </div>
            <div class="panel-body">
                А ни чем
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Чем мы отличаемся от других?
            </div>
            <div class="panel-body">
                А ни чем
            </div>
        </div>
    </div>
</div>