<?php /** @var \Index\Block\Index $this */ ?>
<center><h1>altaifisher.ru богатство водоёмов Алтая</h1></center>
<h2 style="font-size: 16px;">Сообщество рыболовов Алтай, это место для тех кто, сдесь мы делимся своими впечатлениями о поездках на природу,
рыбалке, активном образе жизни, законах, запретах,сдесь вы можете продать снасти и купить снасти для своей рыбалке! Так жже сообщество
может организовать для вас царские охоты и рыбалки!</h2>

<h3>Погода в крае:</h3>

<div class="row">
    <?php $phobos = $this->getPhobos() ?>
    <?php foreach ($phobos as  $_ph): ?>

    <div class="col-lg-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $_ph['date']?>
            </div>
            <div class="panel-body">
                <img src="<?php echo $_ph['icon'] ?>" />
                <br/>
                <?php echo $_ph['weather'] ?>
                <br/>
                температура:<?php echo $_ph['temperature'] ?>
                ветер:<br/>
                &nbsp; -скорость:<?php echo $_ph['wind']['speed'] ?><br/>
                &nbsp; -азимут:<?php echo $_ph['wind']['deg'] ?>
            </div>
        </div>
    </div>
    <?php endforeach;?>
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Клёв рыбы
            </div>
            <div class="panel-body">
                <div style="text-align:center;width:300px;height:240px">
                    <a href="http://orybe.com" title="Лунный прогноз клёва рыбы">Лунный прогноз клёва рыбы</a><br />
                    <iframe src='http://orybe.com/widget_luna_klev.php' width='300' height='240' scrolling='no' frameborder='0'></iframe>
                </div>
                <p>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Немного о правилах сообщества
            </div>
            <div class="panel-body">
                1. Материться не воспрещаеться ( воспрещаеться использования мата, как ругательство адрессованное к другому участнку сообщества)
                </br>
                2. Публикация материалов не относящихся к теме сообщества. </br>
                3. Приветствуеться отчёта с водоёмов Алтая.</br>
            </div>
        </div>
    </div>
</div>