<?php /** @var Index_Block_Index $this */ ?>
<script>
    function ajaxEdit(id) {
        var urlQuery = '<?php echo \Core\App::getBaseUrl() ?>contact/create/renderModal/id/' + id + '/isAjax/true/';
        $.ajax({
            url: urlQuery,
            dataType: 'json',
            success: function (done) {
                $('.modal-body').html(done.html);
                $('#idBtn').trigger('click');
                $('#form_create').validator();
            }
        });
    }
</script>
<?php if ($this->getCountContacts()->cnt == 0): ?>
    <div class="page-header">
        <h1>Contact list</h1>
        <p class="lead">Your don't have contacts</p>
        <?php $this->getChunk('chunks/_message.phtml') ?>
    </div>
<?php else: ?>
    <div class="page-header">
        <h1>Contact list</h1>
        <p class="lead">Your contacts list</p>
        <?php $this->getChunk('chunks/_message.phtml') ?>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <?php
                // generate greed
                $idAttrShow = array();
                ?>
                <td>id</td>
                <td>Name</td>
                <?php foreach ($this->getGreedAttribute() as $_attr): ?>
                    <td><?php
                        $idAttrShow[] = $_attr['id'];
                        echo $_attr['name'];
                        ?></td>
                <?php endforeach; ?>
                <td>Action</td>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->getAllContacts() as $_key => $_contact): ?>
                <tr>
                    <td><?php echo $_key ?></td>
                    <td><?php echo $_contact['name'] ?></td>
                    <?php foreach ($idAttrShow as $_id): ?>
                        <?php if (isset($_contact[$_id])): ?>
                            <td><?php echo $_contact[$_id] ?></td>
                        <?php else: ?>
                            <td>-</td>
                        <?php endif; ?>
                    <?php endforeach ?>
                    <td>
                        <button class="btn btn-primary"
                                onclick="ajaxEdit(<?php echo $_key ?>)">
                            Edit
                        </button>
                        <button class="btn btn-primary"
                                onclick="window.location = '<?php echo \Core\App::getBaseUrl() ?>contact/index/delete/id/<?php echo $_key
                                ?>'"
                        >Delete
                        </button>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>
<button class="btn btn-success" type="button" id="idBtn" data-toggle="modal" data-target="#modalCreate">Add
    contact
</button>
<p class="lead">Manage contact attributes</p>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <td>id</td>
            <td>name</td>
            <td>action</td>
        </tr>
        </thead>
        <?php foreach ($this->getAllAttribute() as $_key => $_attr): ?>
            <tr>
                <td><?php echo $_attr['id'] ?></td>
                <td><?php echo $_attr['name'] ?></td>
                <td>
                    <button class="btn btn-primary"
                            onclick="window.location = '<?php echo \Core\App::getBaseUrl() ?>contact/index/attrDel/id/<?php echo $_attr['id'] ?>'">
                        Delete
                    </button>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
<button class="btn btn-success"
        onclick="window.location = '<?php echo \Core\App::getBaseUrl() ?>contact/create/addAttribute'">Add new
    attribute
</button>


<div class="modal fade" id="modalCreate" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Create new contact</h4>
            </div>
            <div class="modal-body">
                <?php
                $contMod = new Contact_Controller_Create();
                echo $contMod->renderModalAction();
                ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

