<?php
/** @var \Core\Block\Factory\Grid @this * */
?>
<?php echo $this->_getTitle() ?>
<?php foreach ($this->_prepareButton() as $button): ?>
    <a href="<?php echo $button['href'] ?>" class="btn btn-default"><?php echo $button['title'] ?></a>
<?php endforeach; ?>
<table class="table-bordered table">
    <col width="200px">
    <thead>
    <tr>
        <?php foreach ($this->getColumns() as $_column): ?>
            <th><?php echo \Core\Helper::__($_column['label']) ?></th>
        <?php endforeach; ?>
        <?php if (count($this->_prepareAction())): ?>
            <th><?php echo \Core\Helper::__($this->getActionTitle()) ?></th>
        <?php endif ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->getCollection() as $_collection): ?>
        <tr>
            <?php foreach ($this->getColumns() as $_col): ?>
                <td>
                    <?php if (isset($_col['render'])): ?>
                        <?php echo call_user_func(array($this, $_col['render']), $_collection->{$_col['index']},$_collection) ?>
                    <?php else: ?>
                        <?php echo $_collection->{$_col['index']} ?>
                    <?php endif; ?>
                </td>
            <?php endforeach; ?>
            <?php if (count($this->_prepareAction())): ?>
                <td>
                    <?php foreach ($this->_prepareAction() as $action): ?>
                        <?php
                        if (isset($action['param'])) {
                            $param = $action['param'];
                        } else {
                            $param = $action['index'];
                        }
                        ?>
                        [
                        <a href="<?php echo $action['rout'] ?>/<?php echo $param ?>/<?php echo $_collection->{$action['index']} ?>
                                      "><?php echo \Core\Helper::__($action['label']) ?></a>]
                    <?php endforeach; ?>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<a onclick="window.location.reload()" class="btn btn-default"><span class="glyphicon glyphicon-refresh"></span> </a>
<?php $commonPage = $this->getPageCount() ?>
<?php for ($p = 0; $p < $commonPage; $p++): ?>
    <?php

    $request = '';
    $collapse = '';

    $_request = explode('/', $_SERVER['REQUEST_URI']);

    if (array_search('page', $_request) !== false) {
        $key = array_search('page', $_request) + 1;
        $_request[$key] = $p;
        $request = implode('/', $_request);
        $_request[$key] = 0;
        $collapse = implode('/', $_request);
        $request = str_replace('//', '/', $request);
        $collapse = str_replace('//', '/', $collapse);
    } else {
        $request = rtrim($_SERVER['REQUEST_URI'], '/') . '/page/' . $p;
    }
    ?>
    <?php if ($p == 0): ?>
        <a href="<?php echo $collapse ?>" class="btn btn-default"><?php echo $p ?></a>
    <?php else: ?>
        <a href="<?php echo $request ?>" class="btn btn-default"><?php echo $p ?></a>
    <?php endif; ?>
<?php endfor; ?>
