<?php
/**
 * Created by PhpStorm.
 * User: roman
 * Date: 02.03.16
 * Time: 11:42
 */
class Pages_Block_Comment_Render extends Pages_Block_Abstract {

    /**
     * Pages_Block_Viewmenu constructor.
     */
    public function __construct()
    {
        $this->setTemplate('pages/comment/comment');
        $this->toHtml();
    }

    public function toHtml()
    {
//        $allcomment = $this->getComentPage($this->getPage()['_id']);
//        $allcomment = iterator_to_array($allcomment);
//        $allcomment = reset($allcomment);
//        $allcomment = $allcomment['allcoments'];
//        var_dump($allcomment);die;
        return parent::toHtml(); // TODO: Change the autogenerated stub
    }

}