<?php
/**
 * Created by PhpStorm.
 * User: roman
 * Date: 27.02.16
 * Time: 15:47
 */
class Admin_Block_Page_Menu extends Core_Block_Page_Menu
{

    public function getMenuModules($key = 'menu_admin')
    {
        return parent::getMenuModules($key); // TODO: Change the autogenerated stub
    }

}