<?php
/**
 * Created by PhpStorm.
 * User: roman
 * Date: 27.02.16
 * Time: 15:47
 */
namespace Admin\Block\Page {
    class Menu extends \Core\Block\Page\Menu
    {

        public function getMenuModules($key = 'menu_admin')
        {
            return parent::getMenuModules($key); // TODO: Change the autogenerated stub
        }

    }
}