<div class="page-header">
    <h1>Post generator for sites</h1>
    <p>Post generator</p>
</div>
<form action="<?php echo Core_Helper::getUrl('postgen/index/viewResp') ?>" method="post" role="form">
    <button class="btn-success btn-lg btn col-sm-offset-10 " >Submit form</button>
    <div class="form-group">
        <label for="action">Action for request</label>
        <input type="text" class="form-control" name="action" id="action" placeholder="action form"/>
    </div>
    <div class="form-group">
        <label for="user_agent">User Agent</label>
        <input type="text" class="form-control" name="user_agent" id="user_agent" placeholder="User agent" value="<?php echo $this->getUserAgent() ?>"/>
    </div>
    <div class="form-group">
        <label for="content_type">Content type</label>
        <input type="text" class="form-control" name="content_type" id="content_type" placeholder="Content type" value="text/html"/>
    </div>
    <div class="form-group">
        <label for="port">Port</label>
        <input type="text" class="form-control" name="port" id="port" value="80"/>
    </div>
    <div class="page-header">
        <h2>Fields for request</h2>
    </div>
    <?php for($i=0;$i<15;$i++): ?>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <input type="text" class="form-control" name="post[<?php echo $i?>][name]" id="method"
                       placeholder="Method request post,get,delete"/>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <input type="text" class="form-control" name="post[<?php echo $i ?>][value]" id="method"
                       placeholder="Method request post,get,delete"/>
            </div>
        </div>
    </div>
    <?php endfor; ?>

    <div class="page-header">
        <h2>Cookies</h2>
    </div>
    <?php for($i=0;$i<15;$i++): ?>
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <input type="text" class="form-control" name="cookie[<?php echo $i?>][name]" id="method"
                           placeholder="Method request post,get,delete"/>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <input type="text" class="form-control" name="cookie[<?php echo $i ?>][value]" id="method"
                           placeholder="Method request post,get,delete"/>
                </div>
            </div>
        </div>
    <?php endfor; ?>

</form>