<?php
/** @var Pages_Block_View $this */
$page = $this->getPage();
?>
<div class="page-header">
    <h1><?php echo $page['title'] ?></h1>
</div>
<p>
    <?php echo nl2br($page['content']) ?>
</p>
<?php if ($this->getComentPage($page['_id'])->count()): ?>
    <?php foreach ($this->getComentPage($page['_id']) as $_comment): ?>
        <?php foreach ($_comment['allcoments'] as $_key => $_comment): ?>
            <div class="panel-default panel">
                <div class="panel-heading"><?php echo $_comment['name']?></div>
                <div class="panel-body"><?php echo $_comment['comment']?></div>
                <div class="panel-footer">testing|testing|tes</div>
            </div>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif; ?>
<form method="post" action="<?php echo Core_Helper::getUrl('pages/view/addComment') ?>" role="form">
    <input id="comm_id" type="hidden" name="parent" value="">
    <input type="hidden" name="page_id" value="<?php echo $page['_id'] ?>">
    <input type="hidden" name="back_url"
           value="<?php echo Core_App::getBaseUrl() . trim($_SERVER['REQUEST_URI'], '/') ?>">
    <div class="form-group">
        <label for="name">Your name:</label>
        <input class="form-control" id="name" name="name">
    </div>
    <div class="form-group">
        <label for="comment">Your comment:</label>
        <textarea class="form-control" id="comment" name="comment"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Send you comment</button>
</form>
