<!--<ul class="nav nav-list bs-docs-sidenav affix">-->
<!--    <li><i class="chevron-right"></i> <a href="t">stnstn</a></li>-->
<!--    <li><i class="chevron-right"></i> <a href="t">stnstn</a></li>-->
<!--    <li><i class="chevron-right"></i> <a href="t">stnstn</a></li>-->
<!--    <li class="active"><i class="chevron-right"></i> <a href="t">stnstn</a></li>-->
<!--</ul>-->
<!--<div class="col-md">-->
<!--    <a class="btn btn-primary btn-group">testing</a>-->
<!--    <a class="btn btn-primary btn-group">testing234234234</a>-->
<!--    <a class="btn btn-primary btn-group">testing</a>-->
<!--</div>
-->
<div class="well">
<ul class="nav nav-stacked">
    <li class="active"><a href="tns">stnsn</a></li>
    <li class="active"><a href="tns">stnsn</a></li>
    <li class="active"><a href="tns">stnsn</a></li>
    <li class="active"><a href="tns">stnsn</a></li>
    <li class="active"><a href="tns">stnsn</a></li>
</ul>
</div>