<?php /** @var \Core\Block\Factory\Form $this */ ?>
<form <?php
foreach ($this->getFormOptions() as $key => $value) {
    echo $key . '="'
        . $value . '"';
}
?> >
    <?php foreach ($this->getFormElements() as $_element): ?>
        <?php if ($_element['type'] == 'text'): ?>
            <div class="form-group">
                <label
                    for="<?php echo $_element['options']['id'] ?>"><?php echo \Core\Helper::__($_element['options']['label']) ?></label>
                <input
                    type="text" <?php
                foreach ($_element['options'] as $kEl => $kVal) {
                    if ($kEl == 'label') continue;
                    echo $kEl . '="' . $kVal . '"';
                }
                ?>
                >
            </div>
        <?php elseif ($_element['type'] == 'file'): ?>
            <div class="form-group">
                <label
                    for="<?php echo $_element['options']['id'] ?>"><?php echo \Core\Helper::__($_element['options']['label']) ?></label>
                <input
                    type="file" <?php
                foreach ($_element['options'] as $kEl => $kVal) {
                    if ($kEl == 'label') continue;
                    echo $kEl . '="' . $kVal . '"';
                }
                ?>
                >
            </div>
        <?php elseif
        ($_element['type'] == 'textarea'
        ): ?>
            <label
                for="<?php echo $_element['options']['id'] ?>"><?php echo \Core\Helper::__($_element['options']['label']) ?></label>
            <div class="panel panel-default">
            <div class="panel-heading">
                <div class="btn-group " role="group" aria-label="Basic example">
                    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal"><span
                            class="glyphicon glyphicon-picture"></span></button>
                    <button type="button" id="bolt" class="btn btn-default"><span
                            class="glyphicon glyphicon-bold"></span></button>
                    <button type="button" id="italic" class="btn btn-default"><span
                            class="glyphicon glyphicon-italic"></span></button>
                </div>
            </div>
            <div class="panel-body">
            <textarea <?php
            foreach ($_element['options'] as $kEl => $kVal) {
                if ($kEl == 'label') continue;
                if ($kEl == 'value') continue;
                echo $kEl . '="' . $kVal . '"';
            } ?> ><?php echo $_element['options']['value'] ?></textarea>
            </div>

        <?php elseif ($_element['type'] == 'hidden'): ?>
            <input type="hidden"
                <?php
                foreach ($_element['options'] as $kEl => $kVal) {
                    if ($kEl == 'label') continue;
                    echo $kEl . '="' . $kVal . '"';
                }
                ?> />
        <?php elseif ($_element['type'] == 'submit'): ?>
            <div class="panel-footer">

                <!--            <input type="submit" name="sub" value="submit">-->
                <button
                    type="submit"
                    name="<?php echo $_element['options']['name'] ?>"
                    id="<?php echo $_element['options']['id'] ?>"
                    class="<?php echo $_element['options']['class'] ?>"
                >
                    <?php if (isset($_element['options']['icon'])): ?>
                        <span class="<?php echo $_element['options']['icon'] ?>"></span>
                    <?php endif; ?>
                    <?php echo $_element['options']['label'] ?>
                </button>
            </div>
            </div>

        <?php endif; ?>
    <?php endforeach; ?>
</form>

<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type="button" data-dismiss="modal">×</button>
                <h4 class="modal-title">Выберите изображение для вставки</h4>
            </div>
            <div class="modal-body">
                <form id="img">
                    <?php
                    $photo = new \Customer\Block\Photo\Index();
                    ?>
                    <?php foreach ($photo->getAllFile() as $_photo): ?>
                        <input type="radio" name="photo" class="js-pic"
                               value="<?php echo $photo->getUrlToPicture() . $_photo['name']; ?>"/>
                        <img width="150px" src="<?php echo $photo->getUrlToPicture() . $_photo['name']; ?>"/>
                    <?php endforeach; ?>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="chose_pic">Выбрать фото</button>
                <button class="btn btn-default" type="button" id="close_modal" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<script>

    // Флаги для определения браузеров
    var uagent = navigator.userAgent.toLowerCase();
    var is_safari = ( (uagent.indexOf('safari') != -1) || (navigator.vendor == "Apple Computer, Inc.") );
    var is_ie = ( (uagent.indexOf('msie') != -1) && (!is_opera) && (!is_safari) && (!is_webtv) );
    var is_ie4 = ( (is_ie) && (uagent.indexOf("msie 4.") != -1) );
    var is_moz = (navigator.product == 'Gecko');
    var is_ns = ( (uagent.indexOf('compatible') == -1) && (uagent.indexOf('mozilla') != -1) && (!is_opera) && (!is_webtv) && (!is_safari) );
    var is_ns4 = ( (is_ns) && (parseInt(navigator.appVersion) == 4) );
    var is_opera = (uagent.indexOf('opera') != -1);
    var is_kon = (uagent.indexOf('konqueror') != -1);
    var is_webtv = (uagent.indexOf('webtv') != -1);

    var is_win = ( (uagent.indexOf("win") != -1) || (uagent.indexOf("16bit") != -1) );
    var is_mac = ( (uagent.indexOf("mac") != -1) || (navigator.vendor == "Apple Computer, Inc.") );
    var ua_vers = parseInt(navigator.appVersion);

    // Сама функция
    function getSelection(textarea) {
        var selection = null;
        if ((ua_vers >= 4) && is_ie && is_win) {
            if (textarea.isTextEdit) {
                textarea.focus();
                var sel = document.selection;
                var rng = sel.createRange();
                rng.collapse;
                if ((sel.type == "Text" || sel.type == "None") && rng != null)
                    selection = rng.text;
            }
        } else if (typeof(textarea.selectionEnd) != "undefined") {
            selection = (textarea.value).substring(textarea.selectionStart, textarea.selectionEnd);
        }
        return selection;
    }

    $('#chose_pic').on('click', function () {
        var url = $('.js-pic:checked').attr('value');
        var img = '<a href="' + url + '"> <img width="100px" src="' + url + '" /></a>';
        $('#close_modal').trigger('click');
        $('#message').insertAtCaret(img);
    });

    $('#bolt').on('click', function () {
        var select = $('#message').getSelection();
        $('#message').insertAtCaret('<b>' + select.text + '</b>');
    });

    $('#italic').on('click', function () {
        var select = $('#message').getSelection();
        $('#message').insertAtCaret('<i>' + select.text + '</i>');
    });
</script>