<div class="panel panel-success">
    <div class="panel-heading"><?php echo Core_Helper::__('About configuration')?></div>
    <div class="panel-body">
        If configuration
    </div>
</div>

<div class="panel panel-success">
    <div class="panel-heading"><?php echo Core_Helper::__('Documentation')?></div>
    <div class="panel-body">
        You can find documentation about develop on NCMS in folder documentation in root application.
    </div>
</div>

<div class="panel panel-success">
    <div class="panel-heading"><?php echo Core_Helper::__('Cms page')?></div>
    <div class="panel-body">
        If you want create cms page, you can do it by this <a href="/adminpanel/pages">link</a>
    </div>
</div>