<footer class="panel-footer navbar-btn">
    <div class="container">
        <div class="row">
            <p class="text-center">&copy;2016 <a href="http://altaifisher.ru/">AltaiFisher.ru</a></p>
        </div>
        <div class="row">
            <div class="col-sm-4"><a
                    href="http://altaifisher.ru/forum/index/view/trade/video/trade_id/57af69d3fed56a0477680747">
                    Видео о рыбалке</a>
            </div>
            <div class="col-sm-4">
                <a href="http://altaifisher.ru/forum/index/view/trade/photo">
                    Фотогаллерея
                </a>
            </div>
            <div class="col-sm-4">
                <a href="http://altaifisher.ru/forum/index/index">Форум</a>
            </div>
        </div>
        <a href="//8500.ru/cat/"><img src="//8500.ru/8500.ru.2.png" alt="Каталог сайтов"></a>
        <script src="http://ma-static.ru/168534.js" type="text/javascript"></script>
        <!-- Yandex.Metrika informer --> <a href="https://metrika.yandex.ru/stat/?id=39004590&amp;from=informer"
                                            target="_blank" rel="nofollow"><img
                src="https://informer.yandex.ru/informer/39004590/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
                style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика"
                title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)"
                class="ym-advanced-informer" data-cid="39004590" data-lang="ru"/></a> <!-- /Yandex.Metrika informer -->
        <!-- Yandex.Metrika counter -->
        <script type="text/javascript"> (function (d, w, c) {
                (w[c] = w[c] || []).push(function () {
                    try {
                        w.yaCounter39004590 = new Ya.Metrika({
                            id: 39004590,
                            clickmap: true,
                            trackLinks: true,
                            accurateTrackBounce: true,
                            webvisor: true
                        });
                    } catch (e) {
                    }
                });
                var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () {
                    n.parentNode.insertBefore(s, n);
                };
                s.type = "text/javascript";
                s.async = true;
                s.src = "https://mc.yandex.ru/metrika/watch.js";
                if (w.opera == "[object Opera]") {
                    d.addEventListener("DOMContentLoaded", f, false);
                } else {
                    f();
                }
            })(document, window, "yandex_metrika_callbacks"); </script>
        <noscript>
            <div><img src="https://mc.yandex.ru/watch/39004590" style="position:absolute; left:-9999px;" alt=""/></div>
        </noscript> <!-- /Yandex.Metrika counter -->
        <!--LiveInternet counter-->
        <script type="text/javascript"><!--
            document.write("<a href='//www.liveinternet.ru/click' " +
                "target=_blank><img src='//counter.yadro.ru/hit?t14.6;r" +
                escape(document.referrer) + ((typeof(screen) == "undefined") ? "" :
                ";s" + screen.width + "*" + screen.height + "*" + (screen.colorDepth ?
                    screen.colorDepth : screen.pixelDepth)) + ";u" + escape(document.URL) +
                ";" + Math.random() +
                "' alt='' title='LiveInternet: number of pageviews for 24 hours," +
                " of visitors for 24 hours and for today is shown' " +
                "border='0' width='88' height='31'><\/a>")
            //--></script><!--/LiveInternet-->
        <!-- Rating@Mail.ru counter -->
        <script type="text/javascript">
            var _tmr = window._tmr || (window._tmr = []);
            _tmr.push({id: "2804067", type: "pageView", start: (new Date()).getTime()});
            (function (d, w, id) {
                if (d.getElementById(id)) return;
                var ts = d.createElement("script");
                ts.type = "text/javascript";
                ts.async = true;
                ts.id = id;
                ts.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//top-fwz1.mail.ru/js/code.js";
                var f = function () {
                    var s = d.getElementsByTagName("script")[0];
                    s.parentNode.insertBefore(ts, s);
                };
                if (w.opera == "[object Opera]") {
                    d.addEventListener("DOMContentLoaded", f, false);
                } else {
                    f();
                }
            })(document, window, "topmailru-code");
        </script>
        <noscript>
            <div style="position:absolute;left:-10000px;">
                <img src="//top-fwz1.mail.ru/counter?id=2804067;js=na" style="border:0;" height="1" width="1"
                     alt="Рейтинг@Mail.ru"/>
            </div>
        </noscript>
        <!-- //Rating@Mail.ru counter -->
        <!-- Rating@Mail.ru logo -->
        <a href="http://top.mail.ru/jump?from=2804067">
            <img src="//top-fwz1.mail.ru/counter?id=2804067;t=479;l=1"
                 style="border:0;" height="31" width="88" alt="Рейтинг@Mail.ru"/></a>
        <!-- //Rating@Mail.ru logo -->
        <!-- begin of Top100 code -->

        <script id="top100Counter" type="text/javascript" src="http://counter.rambler.ru/top100.jcn?4439894"></script>
        <noscript>
            <a href="http://top100.rambler.ru/navi/4439894/">
                <img src="http://counter.rambler.ru/top100.cnt?4439894" alt="Rambler's Top100" border="0"/>
            </a>

        </noscript>
        <!-- end of Top100 code -->
        <?php if ($_SERVER['REQUEST_URI'] == '/'): ?>
            <script type="text/javascript" src="http://mobtop.ru/c/112363.js"></script>
            <noscript><a href="http://mobtop.ru/in/112363"><img src="http://mobtop.ru/112363.gif"
                                                                alt="MobTop.Ru - Рейтинг и статистика мобильных сайтов"/></a>
            </noscript>
        <?php else: ?>
            <script type="text/javascript" src="http://mobtop.ru/c/112364.js"></script>
            <noscript><a href="http://mobtop.ru/in/112364"><img src="http://mobtop.ru/112364.gif"
                                                                alt="MobTop.Ru - Рейтинг и статистика мобильных сайтов"/></a>
            </noscript>
        <?php endif; ?>
    </div>
</footer>

