<?php
/** @var Core_Block_Page_Head $this */
$pageInfo =  $this->getPageConfig();
?>
<title><?php echo isset($pageInfo['title']) ? $pageInfo['title'] : '' ?></title>
<meta charset="UTF-8">
<!--<link rel="stylesheet" href="--><?php //echo Core_App::getBaseUrl().'static/main.css' ?><!--" />-->
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
<script type="text/javascript" src="<?php echo Core_App::getBaseUrl().'static/function.js' ?>"></script>
<link rel="stylesheet" href="<?php echo Core_App::getBaseUrl()?>static/css/bootstrap.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo Core_App::getBaseUrl().'static/js/bootstrap.js' ?>"></script>
<script type="text/javascript" src="<?php echo Core_App::getBaseUrl().'static/js/validator.js' ?>"></script>
<script>
    $(function() {
        $('#form_create').validator()
    });
</script>
