<?php /** @var \Core\Block\Page\Menu $this */
//    echo \Core\Helper::getUrl('/');die;
?>

<nav class="navbar-static-top navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" data-target="#navbar" data-toggle="collapse" type="button">
                <span class="sr-only">
                    Toggle navigation
                </span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <?php foreach($this->getMenuModules() as $_menu): ?>
                    <li <?php if($this->getCurrentActive() == $_menu['label']) echo 'class="active"'?>>
                        <a href="<?php echo \Core\Helper::getUrl($_menu['rout']) ?>">
                            <?php if(isset($_menu['icon'])) echo '<span class="'.$_menu['icon'].'"></span>'; ?>
                            <?php echo \Core\Helper::__($_menu['label']) ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</nav>
<!--<div class="clearfix">&nbsp;</div>-->
<!--<div class="clearfix">&nbsp;</div>-->
<!--<div class="clearfix">&nbsp;</div>-->
<!--<div class="clearfix">&nbsp;</div>-->