<!--<footer class="panel-footer navbar-btn">-->
<!--    <div class="container">-->
<!--        <div class="row">-->
<!--            <p class="text-center">This is footer part</p>-->
<!--        </div>-->
<!--        <div class="row">-->
<!--            <div class="col-sm-4">test1</div>-->
<!--            <div class="col-sm-4">test12</div>-->
<!--            <div class="col-sm-4">test13</div>-->
<!--        </div>-->
<!--        <div class="row">-->
<!--            <div class="col-sm-4">test</div>-->
<!--            <div class="col-sm-4">test</div>-->
<!--        </div>-->
<!--        <div class="row">-->
<!--            <div class="col-sm-4">test</div>-->
<!--            <div class="col-sm-4">test</div>-->
<!--        </div>-->
<!--    </div>-->
<!--</footer>-->