<?php /** @var Core_Block_Page_Menu $this */ ?>
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="<?php echo Core_App::getBaseUrl()?>">NCMS</a>
            <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
                <span class="sr-only">
                    Toggle navigation
                </span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <?php foreach($this->getMenuAdminModules() as $_menu): ?>
                    <li <?php if($this->getCurrentActive() == $_menu['label']) echo 'class="active"'?>>
                        <a href="<?php echo Core_App::getBaseUrl().$_menu['rout'] ?>"><?php echo $_menu['label'] ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>