<?php /** @var Pages_Block_Abstract $this */
//var_dump($this->getPage()['_id']);die('123');
?>
<div class="row">
    <?php if ($this->getComentPage($this->getPage()['_id'])->count()): ?>
    <?php foreach ($this->getComentPage($this->getPage()['_id']) as $_comment): ?>
    <?php foreach ($_comment['allcoments']['comment_tree'] as $_key1 => $_comment): ?>
        <div class="col-sm-12">
            <div class="panel-default panel">
                <div class="panel-heading"><?php echo $_comment['name'] ?></div>
                <div class="panel-body"><?php echo $_comment['comment'] ?></div>
                <div class="panel-footer"><a href="#form"
                                             onclick="commentReply('<?php echo $_comment['name'] ?>','<?php echo $_key1 ?>')">reply</a>
                </div>
                <input type="hidden" name="comment_tree[<?php echo $_key1 ?>][name]"
                       value="<?php echo $_comment['name'] ?>">
                <input type="hidden" name="comment_tree[<?php echo $_key1 ?>][comment]"
                       value="<?php echo $_comment['comment'] ?>">
            </div>
        </div>
    <?php endforeach; ?>
    <?php endforeach; ?>
    <?php endif; ?>
</div>
