<?php /** @var \Core\Block\AbstractClass $this */ ?>
<head>
    <?php $this->getChunk('chunks/_head.phtml', '\Core\Block\Page\Head') ?>
</head>
<body>
<?php $this->getChunk('chunks/_menu.phtml', '\Core\Block\Page\Menu') ?>
<!--<div class="clear">&nbsp;</div>-->
<div class="container container-fluid">
    <div class="panel-body">
    <div class="row" >
        <div class="col-sm-3">
            <?php echo $this->getData('menu') ?>
        </div>
        <div class="col-sm-8">
            <?php echo $this->getData('content') ?>
        </div>
    </div>
    </div>
</div>
</body>
<?php $this->getChunk('chunks/_footer.phtml') ?>
