<div class="panel panel-success">
    <div class="panel-heading"><?php echo Core_Helper::__('Adding render rule')?></div>
    <div class="panel-body">
        <form action="<?php echo Core_App::getBaseUrl().Config_App::getConfig()['adminurl'].'/url/add'?>" method="post" role="form">
            <div class="form-group">
                <label for="from_url"><?php echo Core_Helper::__('From url')?></label>
                <input id="from_url" class="form-control" type="text" name="from_url" required>
            </div>
            <div class="form-group">
                <label for="to_url"><?php echo Core_Helper::__('To url')?></label>
                <input id="to_url" class="form-control" type="text" name="to_url" required>
            </div>
            <input type="hidden" value="<?php echo Urladmin_Model_Url::REWRITE ?>" name="type">
            <button type="submit" class="btn btn-success"><?php echo Core_Helper::__('Save')?></button>
        </form>
    </div>
</div>

<div class="panel panel-success">
    <div class="panel-heading"><?php echo Core_Helper::__('Adding 301 redirect')?></div>
    <div class="panel-body">
        <form action="<?php echo Core_App::getBaseUrl().Config_App::getConfig()['adminurl'].'/url/add'?>" method="post" role="form">
            <div class="form-group">
                <label for="from_url"><?php echo Core_Helper::__('From url')?></label>
                <input id="from_url" class="form-control" type="text" name="from_url" required>
            </div>
            <div class="form-group">
                <label for="to_url"><?php echo Core_Helper::__('To url')?></label>
                <input id="to_url" class="form-control" type="text" name="to_url" required>
            </div>
            <input type="hidden" value="<?php echo Urladmin_Model_Url::REDIRECT ?>" name="type">
            <button type="submit" class="btn btn-success"><?php echo Core_Helper::__('Save')?></button>
        </form>
    </div>
</div>