<div class="panel panel-success">
    <div class="panel-heading"><?php echo \Core\Helper::__('Rout grid')?></div>
    <div class="panel-body">
        <?php if(count($this->getAllRewrite()) > 0) : ?>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <td><?php echo \Core\Helper::__('id')?></td>
                    <td><?php echo \Core\Helper::__('From url')?></td>
                    <td><?php echo \Core\Helper::__('To url')?></td>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->getAllRewrite() as $_rew): ?>
                    <tr>
                        <td><?php echo $_rew['id'] ?></td>
                        <td><?php echo $_rew['from_url'] ?></td>
                        <td><?php echo $_rew['to_url'] ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php else: ?>
            You don't have any rewrite
        <?php endif; ?>
    </div>
</div>

<div class="panel panel-success">
    <div class="panel-heading"><?php echo \Core\Helper::__('301 redirect')?></div>
    <div class="panel-body">
        <?php if(count($this->getAllRedirect()) > 0) : ?>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <td><?php echo \Core\Helper::__('id')?></td>
                        <td><?php echo \Core\Helper::__('From url')?></td>
                        <td><?php echo \Core\Helper::__('To url')?></td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->getAllRedirect() as $_red): ?>
                        <tr>
                            <td><?php echo $_red['id'] ?></td>
                            <td><?php echo $_red['from_url'] ?></td>
                            <td><?php echo $_red['to_url'] ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php else: ?>
            <?php echo \Core\Helper::__('Table is empty')?>
        <?php endif; ?>
    </div>
</div>