<?php /** @var \Admin\Block\Config\Left\Form $this */
?>
<div class="panel panel-success">
    <div class="panel-heading"><?php echo $this->getData('header')?></div>
    <div class="panel-body">
        <form role="form" action="<?php echo $this->getData('action') ?>" method="post">
            <?php foreach($this->getLayerElement() as $element): ?>
                <?php /** @var \Admin\Block\Config\Left\Form\Element $element */ ?>
                <?php $element->toHtml(); ?>
            <?php endforeach; ?>
            <button class="btn btn-success" type="submit">Save</button>
        </form>
    </div>
    <div class="panel-footer"><?php echo $this->getData('footer') ?></div>
</div>
